### PR TITLE
Miscellaneous stylistic improvements

### PR DESCRIPTION
**Pull request by kilianmh**
- replace `concatenate` with `concat`
- replace nested `if` with single `cond`
- replace `unless null` with `when`
- replace `if` without else clause with `when`

### CODE REVIEW

**Comment by vindarel** [comment]
I was seeing an interest in calling the built-in `concatenate`, mainly to show the use of built-ins to new readers. Then it might be slightly more efficient, and more future-proof against a silly `str:concat` change. The other changes are good stylistic practice, this one less sure. What do you think?

**Comment by kilianmh** [comment]
> show the use of built-ins to new readers

Does the function definition of `str:concat` not already show the use of concatenate to new readers of `cl-str`? ;)

> slightly more efficient, and more future-proof against a silly `str:concat` change

In that case the users should quickly find out about `concatenate` in the hyperspec. Alternatively we could mention `concatenate` in a comment / docstring.

**Comment by kilianmh** [comment]
So then you want me to revert `concat` to `concatenate` for now so the other changes can be merged?

**Comment by vindarel** [comment]
> So then you want me to revert `concat` to `concatenate` for now so the other changes can be merged?

yes please :)

**Comment by kilianmh** [comment]
Now it should be as discussed ;)

**Comment by vindarel** [comment]
Thank you again!

**Pull request merged**
