### PR TITLE
add ensure functions

### PR DESCRIPTION
**Pull request by vindarel**
ensure
ensure[prefix, suffi, wrapped-in]
wrapped-in-p

### CODE REVIEW

**Comment by vindarel** [comment]
replaces https://github.com/vindarel/cl-str/pull/76

a last look after a merge mess.

**Review by kilianmh — APPROVED** [review]
in readme:
- line 218: "functions" instead "fonctions" (same in str.lisp line 565)
- line 229: remove "if and only"
- changelog: use `prefixp` instead `prefix?` and `suffixp` instead `suffix?`

ensure function:
 there should probably be a check that `wrapped-in` is not supplied together with `prefix`/`suffix`. Else the `prefix`/`suffix` will be silently ignored. Something like this
```common-lisp
(when (and wrapped-in (or prefix suffix))
  (error "Please only supply either wrapped-in or prefix and/or suffix"))
```

**Comment by vindarel** [comment]
mmh, would you really signal an error?? Why block the execution? Possibly, a warning.

**Comment by vindarel** [comment]
fixed readme,

added a check in ensure: ":wrapped-in" is not the empty string.

Thanks for the reviews!

**Pull request merged**
