### PR TITLE
Add *ignore-case* *omit-nulls*

### PR DESCRIPTION
**Pull request by koji-kojiro**
### TODO
- [x] tests
- [ ] README

related to #14 .

### CODE REVIEW

**Comment by koji-kojiro** [comment]
@vindarel 
I'm not good at writing English...
I wonder if you could update README.

**Comment by koji-kojiro** [comment]
BTW, why don't you use any ci service (such as travis)? (see https://github.com/vindarel/cl-str/pull/16/commits/a923e8c175e9772b8d62b6d9b190bf99506d240b)

**Comment by vindarel** [comment]
for no reason. Good catch, a CI is needed now.

Sure, I will update the readme (but you are decent at english).

**Comment by koji-kojiro** [comment]
google translate is my friend.

**Pull request merged**
