### PR TITLE
add str:downcase and friends, fixing the nil argument surprise.

### LINKED ISSUE #20: cl's string-downcase of nil returns "nil"
(string-downcase nil)
    ;; "nil"

it returns the string "nil" :s 

Good candidate for a `str:downcase`.

Same for `string-upcase` and `string-capitalize`.

### PR DESCRIPTION
**Pull request by vindarel**
fixes #20

### CODE REVIEW

**Comment by vindarel** [comment]
cc @jmercouris and @ambrevar !

**Comment by Ambrevar** [comment]
Beautiful! :)

**Comment by jmercouris** [comment]
Nice! Fantastic :)

now also add: 
```
(defun non-empty-string-p (s)
  (and (stringp s)
       (not (str:emptyp s))))
```

and we won't need to put it in our utility files anymore :D

**Comment by Ambrevar** [comment]
Isn't (not (emptyp s)) shorter?

**Comment by vindarel** [comment]
I guess the difference is the `stringp`, which seems weird to add, but is useful in the context of taking input from the outside (web routes).

**Comment by vindarel** [comment]
Added, along with `non-blank-string-p`.

**Pull request merged**
