### PR TITLE
add s-assoc-value function

### PR DESCRIPTION
**Pull request by travv0**

### CODE REVIEW

**Comment by travv0** [comment]
I saw #31 and I was looking for something to do so I added it, but I forgot to change branches first and I'm not enough of a git guru to know how to separate those two commits into their own branches.

**Comment by vindarel** [comment]
Nice, thanks. Will merge when available!

**Comment by vindarel** [comment]
Ah, there will be a lack of consistency somewhere. `assoc`'s arguments are `item alist`, here `s-assoc-value` respects str's rule to put the string last, so it is `alist item`. At first sight I think we should respect `assoc`'s order, that way it is much less painful to change one's code from `assoc / assoc-value` to `s-assoc-value`.

What do you watchers think?

**Comment by vindarel** [comment]
> I saw #31 and I was looking for something to do so I added it, but I forgot to change branches first and I'm not enough of a git guru to know how to separate those two commits into their own branches.

FYI (that's ok for that PR), you could:
- clone your branch. You now have both master and a new branch with those two commits.
- delete a commit on both branches. I'd do with magit: list the commits (`l l`), rebase interactively (`r i`), and delete a commit there. Or maybe revert one (`v`) and then rebase.

**Comment by travv0** [comment]
I used that argument order for consistency with alexandria's `assoc-value` because it's also inconsistent with `assoc`.

**Comment by vindarel** [comment]
ah a good point, but damn for the inconsistency^^

**Comment by vindarel** [comment]
Then OK. Can you update the readme, the TOC (see the comment on how to do it with an emacs plugin) and speak about those differences with assoc and alexandria:assoc-value ?

**Comment by travv0** [comment]
Sure thing, I'll take care of that stuff when I have a chance.

**Comment by vindarel** [comment]
Hello, and up?

**Comment by travv0** [comment]
Sorry for the delay, let me know if that looks alright.

**Comment by vindarel** [comment]
perfect, thanks!

**Comment by vindarel** [comment]
oops: 

> The second return value is a generalized boolean indicating
   whether the key was found.

it is actually the cons cell. Corrected.

**Pull request merged**
