### PR TITLE
Add functions

### PR DESCRIPTION
**Pull request by amo-susi**
I added new finctions.
string-car, string-cdr and string-nth.

### CODE REVIEW

**Comment by vindarel** [comment]
Hi, thanks for the PR.

I'm not fond of the names. What about `s-first`, `s-rest` ? They're shorter and clearer IMO. (in that case `string-case` can be renamed).

or `first-letter`, `rest-letters`, `nth-letter` ? Other ideas ?

Also you forgot to update the readme.

**Comment by amo-susi** [comment]
Thank you for your reply.
Change the name, and added READEM.md.

**Comment by vindarel** [comment]
Thank you !

**Comment by koji-kojiro** [comment]
FYI, `cl:elt`(or `cl:aref`) can do same thing as `s-nth`.

```lisp
* (elt "test" 1)
#\e
* (string (elt "test" 1))
"e"
```

**Comment by vindarel** [comment]
I add this note in the docstring.

**Pull request merged**
