### PR TITLE
type declarations for join and concat

### LINKED ISSUE #51: Ftype str:concat, etc.
The following 
```lisp
(declaim (ftype (function (quri:uri) string) schemeless-url))
(defun schemeless-url (uri)
  "Return URL without its scheme (e.g. it removes 'https://')."
  (str:concat (quri:uri-authority uri)
              (or (quri:uri-path uri) "/")
              (quri:uri-query uri)
              (quri:uri-fragment uri)))

```

yields

```lisp
    Type assertion too complex to check:
    (VALUES STRING &REST T).
    It allows an unknown number of values, consider using
    (VALUES STRING &OPTIONAL).

```

This is because `concatenate` is too complex to type check for SBCL.
You can fix it by adding an `ftype` to str:concat and maybe wrapping the return value with

```
(the (values string &optional)
    YOUR-RESULT)
```

Same with str:join, str:insert, all functions that use `concatenate`.

### PR DESCRIPTION
**Pull request by vindarel**
fixes #51

### CODE REVIEW

**Comment by Ambrevar** [comment]
What does `(or string)` mean as opposed to `string`?

**Comment by vindarel** [comment]
I want it to accept NIL here. Is `(or nil string)` strictly necessary?

**Comment by Ambrevar** [comment]
NIL is not a type.
The right type would be `(or null string)`.

**Comment by vindarel** [comment]
yeah sure. Indeed it works better. Thanks.

**Comment by Ambrevar** [comment]
I tested with the following and it worked!

```lisp
(declaim (ftype (function ((cons string)) string) foo))
(defun foo (args)
  (str:join " " args))

```

I believe this is good to merge, thanks for fixing it!

**Pull request merged**
