### PR TITLE
Add missing dependency on cl-ppcre. Add functions words/unwords, ...

### PR DESCRIPTION
**Pull request by daapp**
lines/unlines. Add tests.

### CODE REVIEW

**Comment by vindarel** [comment]
Hi, thanks for the PR :) I have a few remarks and questions.

(first, you could have added cl-ppcre in another branch for a separate PR, I'd merged it right away)

**Comment by vindarel** [comment]
And you forgot to update the readme and its table of content.

**Comment by vindarel** [comment]
Out of curiosity, do you use these new verbs and this library somewhere ?

**Comment by daapp** [comment]
I use this library in small backend server for mobile application. Idea of these functions taken from Haskell.

**Comment by vindarel** [comment]
ping ! When you're ready this will make a great addition :)

**Comment by vindarel** [comment]
I finished myslef. Thanks !

**Pull request closed without merging**
